FROM node:latest

LABEL "name"="super.real.deploy"
LABEL "maintainer"="timmy tim tim"
LABEL "version"="0.0.1"

LABEL "com.github.actions.name"="Publish the challenge"
LABEL "com.github.actions.description"="Publish static react website via gh-pages"
LABEL "com.github.actions.icon"="package"
LABEL "com.github.actions.color"="green"
